name: myio-demo
region: nyc
services:
  - name: shiny-app
    dockerfile_path: Dockerfile
    github:
      repo: mortonanalytics/myIO
      branch: main
      deploy_on_push: true
    http_port: 3838
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PROXY_SECRET
        value: ae536a852eb7111946bfe8ae0b48013232ace79bc6cdcbf57108a2d16490da15
        type: SECRET
    routes:
      - path: /
