---
title: "testRmd"
author: "Morton Analytics LLC"
date: "4/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown


```{r cars}
library(dplyr)
library(myIO)
library(viridis)
library(shiny)

df <- datasets::airquality %>%
  mutate(Month = paste0("M", Month),
         Temp_low = Temp * c(0.8,0.9,0.75),
         Temp_high = Temp * c(1.2,1.1,1.3)) %>%
  group_by(Day) %>%
  mutate(Percent = Temp/sum(Temp)) %>%
  ungroup()

colors <- substr(viridis(5), 1, 7)

column(12,
       myIO(width = "100%")%>%
        addIoLayer(type = "line",
                   color = colors,
                   label = "Month",
                   data = df ,
                   mapping = list(
                     x_var = "Day",
                     y_var = "Temp",
                     #low_y = "Temp_low",
                     #high_y = "Temp_high",
                     group = "Month"
                   )) %>%
        #setAxisLimits(xlim = list(min = "1"))%>%
        setToggle(newY = "Percent", newScaleY = ".0%") %>%
        setAxisFormat(yAxis = ".0f")
       )

```

