import { exportToCsv } from "../utils/export-csv.js";
import { getSVGString, svgString2Image } from "../utils/export-svg.js";
import { saveAs } from "../utils/file-saver.js";

export function addButtons(chart, layers) {
  var buttonData = [
    {
      name: "image",
      html: '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 32 32"><title>PNG</title><path d="M9.5 19c0 3.59 2.91 6.5 6.5 6.5s6.5-2.91 6.5-6.5-2.91-6.5-6.5-6.5-6.5 2.91-6.5 6.5zM30 8h-7c-0.5-2-1-4-3-4h-8c-2 0-2.5 2-3 4h-7c-1.1 0-2 0.9-2 2v18c0 1.1 0.9 2 2 2h28c1.1 0 2-0.9 2-2v-18c0-1.1-0.9-2-2-2zM16 27.875c-4.902 0-8.875-3.973-8.875-8.875s3.973-8.875 8.875-8.875c4.902 0 8.875 3.973 8.875 8.875s-3.973 8.875-8.875 8.875zM30 14h-4v-2h4v2z"></path></svg>'
    },
    {
      name: "chart",
      html: '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 -3 35 35"><title>Download Data</title><path d="M26 2h-20l-6 6v21c0 0.552 0.448 1 1 1h30c0.552 0 1-0.448 1-1v-21l-6-6zM16 26l-10-8h6v-6h8v6h6l-10 8zM4.828 6l2-2h18.343l2 2h-22.343z"></path></svg>'
    },
    {
      name: "percent",
      html: '<!-- Generated by IcoMoon.io --><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="-5 -5 32 32"><title>Percent to Number</title><path d="M18.293 4.293l-14 14c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0l14-14c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0zM10 6.5c0-0.966-0.393-1.843-1.025-2.475s-1.509-1.025-2.475-1.025-1.843 0.393-2.475 1.025-1.025 1.509-1.025 2.475 0.393 1.843 1.025 2.475 1.509 1.025 2.475 1.025 1.843-0.393 2.475-1.025 1.025-1.509 1.025-2.475zM8 6.5c0 0.414-0.167 0.788-0.439 1.061s-0.647 0.439-1.061 0.439-0.788-0.167-1.061-0.439-0.439-0.647-0.439-1.061 0.167-0.788 0.439-1.061 0.647-0.439 1.061-0.439 0.788 0.167 1.061 0.439 0.439 0.647 0.439 1.061zM21 17.5c0-0.966-0.393-1.843-1.025-2.475s-1.509-1.025-2.475-1.025-1.843 0.393-2.475 1.025-1.025 1.509-1.025 2.475 0.393 1.843 1.025 2.475 1.509 1.025 2.475 1.025 1.843-0.393 2.475-1.025 1.025-1.509 1.025-2.475zM19 17.5c0 0.414-0.167 0.788-0.439 1.061s-0.647 0.439-1.061 0.439-0.788-0.167-1.061-0.439-0.439-0.647-0.439-1.061 0.167-0.788 0.439-1.061 0.647-0.439 1.061-0.439 0.788 0.167 1.061 0.439 0.439 0.647 0.439 1.061z"></path></svg>'
    },
    {
      name: "group2stack",
      html: '<!-- Generated by IcoMoon.io --><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 32 32"><title>Grouped2Stacked</title><path d="M8 6l-4-4h-2v2l4 4zM10 0h2v4h-2zM18 10h4v2h-4zM20 4v-2h-2l-4 4 2 2zM0 10h4v2h-4zM10 18h2v4h-2zM2 18v2h2l4-4-2-2zM31.563 27.563l-19.879-19.879c-0.583-0.583-1.538-0.583-2.121 0l-1.879 1.879c-0.583 0.583-0.583 1.538 0 2.121l19.879 19.879c0.583 0.583 1.538 0.583 2.121 0l1.879-1.879c0.583-0.583 0.583-1.538 0-2.121zM15 17l-6-6 2-2 6 6-2 2z"></path></svg>'
    }
  ];

  var data2Use = chart.options.toggleY ? (chart.plotLayers[0].type == "groupedBar" ? buttonData : buttonData.slice(0, 3)) : buttonData.slice(0, 2);
  var buttonDiv = d3.select(chart.element).append("div")
    .attr("class", "buttonDiv")
    .style("opacity", 1)
    .style("left", chart.width - (40 + 40 * data2Use.length) + "px")
    .style("top", "0px");

  buttonDiv.selectAll(".button")
    .data(data2Use)
    .enter()
    .append("div")
    .attr("class", "button")
    .html(function(d) {
      return d.html;
    })
    .on("click", function(event, d) {
      if (d.name == "image") {
        var svgString = getSVGString(chart.svg.node());
        svgString2Image(svgString, 2 * chart.width, 2 * chart.height, "png", function(dataBlob) {
          saveAs(dataBlob, chart.element.id + ".png");
        });
      } else if (d.name == "chart") {
        var csvData = [];
        chart.plotLayers.forEach(function(layer) {
          csvData.push(layer.data);
        });
        exportToCsv(chart.element.id + "_data.csv", [].concat.apply([], csvData));
      } else if (d.name == "percent") {
        if (chart.toggleY) {
          if (chart.toggleY[0] == chart.options.toggleY[0]) {
            chart.toggleY = [chart.plotLayers[0].mapping.y_var, chart.options.yAxisFormat];
          } else if (chart.toggleY[0] == chart.plotLayers[0].mapping.y_var) {
            chart.toggleY = chart.options.toggleY;
          }
        } else {
          chart.toggleY = chart.options.toggleY;
        }

        chart.toggleVarY(chart.toggleY);
      } else if (d.name == "group2stack") {
        chart.toggleGroupedLayout(layers);
      }
    });
}
